// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<[u8 ; 8]>>
abstract class U88 implements RustOpaqueInterface {}

class TripleQDES {
  final U8Array6Array16Array3 schdule;

  const TripleQDES({required this.schdule});

  Future<void> cryptInplace({required U88 block}) =>
      RustLib.instance.api.crateApiLyricParserEqrcQdecTripleQdesCryptInplace(
        that: this,
        block: block,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TripleQDES> newInstance({
    required List<int> key,
    required bool isDecrypt,
  }) => RustLib.instance.api.crateApiLyricParserEqrcQdecTripleQdesNew(
    key: key,
    isDecrypt: isDecrypt,
  );

  @override
  int get hashCode => schdule.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripleQDES &&
          runtimeType == other.runtimeType &&
          schdule == other.schdule;
}

class U8Array6 extends NonGrowableListView<int> {
  static const arraySize = 6;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array6(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array6.init() : this(Uint8List(arraySize));
}

class U8Array6Array16 extends NonGrowableListView<U8Array6> {
  static const arraySize = 16;

  @internal
  List<U8Array6> get inner => _inner;
  final List<U8Array6> _inner;

  U8Array6Array16(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  U8Array6Array16.init(U8Array6 fill)
    : this(List<U8Array6>.filled(arraySize, fill));
}

class U8Array6Array16Array3 extends NonGrowableListView<U8Array6Array16> {
  static const arraySize = 3;

  @internal
  List<U8Array6Array16> get inner => _inner;
  final List<U8Array6Array16> _inner;

  U8Array6Array16Array3(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  U8Array6Array16Array3.init(U8Array6Array16 fill)
    : this(List<U8Array6Array16>.filled(arraySize, fill));
}
