// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/logger.dart';
import 'api/lyric_parser.dart';
import 'api/lyric_parser/api.dart';
import 'api/lyric_parser/utils.dart';
import 'api/smtc_flutter.dart';
import 'api/tag_reader.dart';
import 'api/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1416630832;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_icey',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSmtcFlutterSmtcFlutterClose({required SmtcFlutter that});

  SmtcFlutter crateApiSmtcFlutterSmtcFlutterNew();

  Stream<SMTCControlEvent>
  crateApiSmtcFlutterSmtcFlutterSubscribeToControlEvents({
    required SmtcFlutter that,
  });

  Future<void> crateApiSmtcFlutterSmtcFlutterUpdateDisplay({
    required SmtcFlutter that,
    required String title,
    required String artist,
    required String album,
    required int duration,
    required String path,
  });

  Future<void> crateApiSmtcFlutterSmtcFlutterUpdateState({
    required SmtcFlutter that,
    required SMTCState state,
  });

  Future<void> crateApiSmtcFlutterSmtcFlutterUpdateTimeProperties({
    required SmtcFlutter that,
    required int progress,
  });

  Stream<IndexActionState> crateApiTagReaderBuildIndexFromFoldersRecursively({
    required List<String> folders,
    required String indexPath,
  });

  Future<String?> crateApiTagReaderGetLyricFromPath({required String path});

  Future<Uint8List?> crateApiTagReaderGetPictureFromPath({
    required String path,
    required int width,
    required int height,
  });

  Stream<String> crateApiLoggerInitRustLogger();

  Future<bool> crateApiUtilsLaunchInBrowser({required String uri});

  Future<LyricLineOwned> crateApiLyricParserLyricLineOwnedDefault();

  Future<bool> crateApiLyricParserLyricLineOwnedIsEmpty({
    required LyricLineOwned that,
  });

  Future<String> crateApiLyricParserLyricLineOwnedToLine({
    required LyricLineOwned that,
  });

  Future<LyricWordOwned> crateApiLyricParserLyricWordOwnedDefault();

  Future<bool> crateApiLyricParserLyricWordOwnedIsEmpty({
    required LyricWordOwned that,
  });

  Future<List<LyricLineOwned>> crateApiLyricParserApiParseEslrc({
    required String content,
  });

  Future<List<LyricLineOwned>> crateApiLyricParserApiParseLrc({
    required String content,
  });

  Future<List<LyricLineOwned>> crateApiLyricParserApiParseLys({
    required String content,
  });

  Future<List<LyricLineOwned>> crateApiLyricParserApiParseQrc({
    required String content,
  });

  Future<TTMLLyricOwned> crateApiLyricParserApiParseTtml({
    required String content,
  });

  Future<List<LyricLineOwned>> crateApiLyricParserApiParseYrc({
    required String content,
  });

  Future<String?> crateApiUtilsPickSingleFolder();

  Future<void> crateApiLyricParserUtilsProcessLyrics({
    required LyricLine lines,
  });

  Future<bool> crateApiUtilsShowInExplorer({required String path});

  Future<String> crateApiLyricParserApiStringifyAss({
    required List<LyricLineOwned> lines,
  });

  Future<String> crateApiLyricParserApiStringifyEslrc({
    required List<LyricLineOwned> lines,
  });

  Future<String> crateApiLyricParserApiStringifyLrc({
    required List<LyricLineOwned> lines,
  });

  Future<String> crateApiLyricParserApiStringifyLys({
    required List<LyricLineOwned> lines,
  });

  Future<String> crateApiLyricParserApiStringifyQrc({
    required List<LyricLineOwned> lines,
  });

  Future<String> crateApiLyricParserApiStringifyTtml({
    required TTMLLyricOwned ttml,
  });

  Future<String> crateApiLyricParserApiStringifyYrc({
    required List<LyricLineOwned> lines,
  });

  Future<TTMLLyricOwned> crateApiLyricParserTtmlLyricOwnedDefault();

  Stream<IndexActionState> crateApiTagReaderUpdateIndex({
    required String indexPath,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LyricLine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LyricLine;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LyricLinePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SmtcFlutter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SmtcFlutter;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SmtcFlutterPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSmtcFlutterSmtcFlutterClose({
    required SmtcFlutter that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmtcFlutterSmtcFlutterCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmtcFlutterSmtcFlutterCloseConstMeta =>
      const TaskConstMeta(debugName: "SmtcFlutter_close", argNames: ["that"]);

  @override
  SmtcFlutter crateApiSmtcFlutterSmtcFlutterNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmtcFlutterSmtcFlutterNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmtcFlutterSmtcFlutterNewConstMeta =>
      const TaskConstMeta(debugName: "SmtcFlutter_new", argNames: []);

  @override
  Stream<SMTCControlEvent>
  crateApiSmtcFlutterSmtcFlutterSubscribeToControlEvents({
    required SmtcFlutter that,
  }) {
    final sink = RustStreamSink<SMTCControlEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
              that,
              serializer,
            );
            sse_encode_StreamSink_smtc_control_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta:
              kCrateApiSmtcFlutterSmtcFlutterSubscribeToControlEventsConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiSmtcFlutterSmtcFlutterSubscribeToControlEventsConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_subscribe_to_control_events",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiSmtcFlutterSmtcFlutterUpdateDisplay({
    required SmtcFlutter that,
    required String title,
    required String artist,
    required String album,
    required int duration,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
            that,
            serializer,
          );
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          sse_encode_String(album, serializer);
          sse_encode_u_32(duration, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmtcFlutterSmtcFlutterUpdateDisplayConstMeta,
        argValues: [that, title, artist, album, duration, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmtcFlutterSmtcFlutterUpdateDisplayConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_update_display",
        argNames: ["that", "title", "artist", "album", "duration", "path"],
      );

  @override
  Future<void> crateApiSmtcFlutterSmtcFlutterUpdateState({
    required SmtcFlutter that,
    required SMTCState state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
            that,
            serializer,
          );
          sse_encode_smtc_state(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmtcFlutterSmtcFlutterUpdateStateConstMeta,
        argValues: [that, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmtcFlutterSmtcFlutterUpdateStateConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_update_state",
        argNames: ["that", "state"],
      );

  @override
  Future<void> crateApiSmtcFlutterSmtcFlutterUpdateTimeProperties({
    required SmtcFlutter that,
    required int progress,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
            that,
            serializer,
          );
          sse_encode_u_32(progress, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmtcFlutterSmtcFlutterUpdateTimePropertiesConstMeta,
        argValues: [that, progress],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSmtcFlutterSmtcFlutterUpdateTimePropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "SmtcFlutter_update_time_properties",
        argNames: ["that", "progress"],
      );

  @override
  Stream<IndexActionState> crateApiTagReaderBuildIndexFromFoldersRecursively({
    required List<String> folders,
    required String indexPath,
  }) {
    final sink = RustStreamSink<IndexActionState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_list_String(folders, serializer);
            sse_encode_String(indexPath, serializer);
            sse_encode_StreamSink_index_action_state_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiTagReaderBuildIndexFromFoldersRecursivelyConstMeta,
          argValues: [folders, indexPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiTagReaderBuildIndexFromFoldersRecursivelyConstMeta =>
      const TaskConstMeta(
        debugName: "build_index_from_folders_recursively",
        argNames: ["folders", "indexPath", "sink"],
      );

  @override
  Future<String?> crateApiTagReaderGetLyricFromPath({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTagReaderGetLyricFromPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTagReaderGetLyricFromPathConstMeta =>
      const TaskConstMeta(debugName: "get_lyric_from_path", argNames: ["path"]);

  @override
  Future<Uint8List?> crateApiTagReaderGetPictureFromPath({
    required String path,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTagReaderGetPictureFromPathConstMeta,
        argValues: [path, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTagReaderGetPictureFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "get_picture_from_path",
        argNames: ["path", "width", "height"],
      );

  @override
  Stream<String> crateApiLoggerInitRustLogger() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiLoggerInitRustLoggerConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLoggerInitRustLoggerConstMeta =>
      const TaskConstMeta(debugName: "init_rust_logger", argNames: ["sink"]);

  @override
  Future<bool> crateApiUtilsLaunchInBrowser({required String uri}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsLaunchInBrowserConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsLaunchInBrowserConstMeta =>
      const TaskConstMeta(debugName: "launch_in_browser", argNames: ["uri"]);

  @override
  Future<LyricLineOwned> crateApiLyricParserLyricLineOwnedDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lyric_line_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserLyricLineOwnedDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserLyricLineOwnedDefaultConstMeta =>
      const TaskConstMeta(debugName: "lyric_line_owned_default", argNames: []);

  @override
  Future<bool> crateApiLyricParserLyricLineOwnedIsEmpty({
    required LyricLineOwned that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_lyric_line_owned(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserLyricLineOwnedIsEmptyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserLyricLineOwnedIsEmptyConstMeta =>
      const TaskConstMeta(
        debugName: "lyric_line_owned_is_empty",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiLyricParserLyricLineOwnedToLine({
    required LyricLineOwned that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_lyric_line_owned(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserLyricLineOwnedToLineConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserLyricLineOwnedToLineConstMeta =>
      const TaskConstMeta(
        debugName: "lyric_line_owned_to_line",
        argNames: ["that"],
      );

  @override
  Future<LyricWordOwned> crateApiLyricParserLyricWordOwnedDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lyric_word_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserLyricWordOwnedDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserLyricWordOwnedDefaultConstMeta =>
      const TaskConstMeta(debugName: "lyric_word_owned_default", argNames: []);

  @override
  Future<bool> crateApiLyricParserLyricWordOwnedIsEmpty({
    required LyricWordOwned that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_lyric_word_owned(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserLyricWordOwnedIsEmptyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserLyricWordOwnedIsEmptyConstMeta =>
      const TaskConstMeta(
        debugName: "lyric_word_owned_is_empty",
        argNames: ["that"],
      );

  @override
  Future<List<LyricLineOwned>> crateApiLyricParserApiParseEslrc({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lyric_line_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiParseEslrcConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiParseEslrcConstMeta =>
      const TaskConstMeta(debugName: "parse_eslrc", argNames: ["content"]);

  @override
  Future<List<LyricLineOwned>> crateApiLyricParserApiParseLrc({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lyric_line_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiParseLrcConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiParseLrcConstMeta =>
      const TaskConstMeta(debugName: "parse_lrc", argNames: ["content"]);

  @override
  Future<List<LyricLineOwned>> crateApiLyricParserApiParseLys({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lyric_line_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiParseLysConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiParseLysConstMeta =>
      const TaskConstMeta(debugName: "parse_lys", argNames: ["content"]);

  @override
  Future<List<LyricLineOwned>> crateApiLyricParserApiParseQrc({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lyric_line_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiParseQrcConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiParseQrcConstMeta =>
      const TaskConstMeta(debugName: "parse_qrc", argNames: ["content"]);

  @override
  Future<TTMLLyricOwned> crateApiLyricParserApiParseTtml({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ttml_lyric_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiParseTtmlConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiParseTtmlConstMeta =>
      const TaskConstMeta(debugName: "parse_ttml", argNames: ["content"]);

  @override
  Future<List<LyricLineOwned>> crateApiLyricParserApiParseYrc({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lyric_line_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiParseYrcConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiParseYrcConstMeta =>
      const TaskConstMeta(debugName: "parse_yrc", argNames: ["content"]);

  @override
  Future<String?> crateApiUtilsPickSingleFolder() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsPickSingleFolderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsPickSingleFolderConstMeta =>
      const TaskConstMeta(debugName: "pick_single_folder", argNames: []);

  @override
  Future<void> crateApiLyricParserUtilsProcessLyrics({
    required LyricLine lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
            lines,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserUtilsProcessLyricsConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserUtilsProcessLyricsConstMeta =>
      const TaskConstMeta(debugName: "process_lyrics", argNames: ["lines"]);

  @override
  Future<bool> crateApiUtilsShowInExplorer({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsShowInExplorerConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsShowInExplorerConstMeta =>
      const TaskConstMeta(debugName: "show_in_explorer", argNames: ["path"]);

  @override
  Future<String> crateApiLyricParserApiStringifyAss({
    required List<LyricLineOwned> lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_lyric_line_owned(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyAssConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyAssConstMeta =>
      const TaskConstMeta(debugName: "stringify_ass", argNames: ["lines"]);

  @override
  Future<String> crateApiLyricParserApiStringifyEslrc({
    required List<LyricLineOwned> lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_lyric_line_owned(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyEslrcConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyEslrcConstMeta =>
      const TaskConstMeta(debugName: "stringify_eslrc", argNames: ["lines"]);

  @override
  Future<String> crateApiLyricParserApiStringifyLrc({
    required List<LyricLineOwned> lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_lyric_line_owned(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyLrcConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyLrcConstMeta =>
      const TaskConstMeta(debugName: "stringify_lrc", argNames: ["lines"]);

  @override
  Future<String> crateApiLyricParserApiStringifyLys({
    required List<LyricLineOwned> lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_lyric_line_owned(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyLysConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyLysConstMeta =>
      const TaskConstMeta(debugName: "stringify_lys", argNames: ["lines"]);

  @override
  Future<String> crateApiLyricParserApiStringifyQrc({
    required List<LyricLineOwned> lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_lyric_line_owned(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyQrcConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyQrcConstMeta =>
      const TaskConstMeta(debugName: "stringify_qrc", argNames: ["lines"]);

  @override
  Future<String> crateApiLyricParserApiStringifyTtml({
    required TTMLLyricOwned ttml,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ttml_lyric_owned(ttml, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyTtmlConstMeta,
        argValues: [ttml],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyTtmlConstMeta =>
      const TaskConstMeta(debugName: "stringify_ttml", argNames: ["ttml"]);

  @override
  Future<String> crateApiLyricParserApiStringifyYrc({
    required List<LyricLineOwned> lines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_lyric_line_owned(lines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserApiStringifyYrcConstMeta,
        argValues: [lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserApiStringifyYrcConstMeta =>
      const TaskConstMeta(debugName: "stringify_yrc", argNames: ["lines"]);

  @override
  Future<TTMLLyricOwned> crateApiLyricParserTtmlLyricOwnedDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ttml_lyric_owned,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLyricParserTtmlLyricOwnedDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLyricParserTtmlLyricOwnedDefaultConstMeta =>
      const TaskConstMeta(debugName: "ttml_lyric_owned_default", argNames: []);

  @override
  Stream<IndexActionState> crateApiTagReaderUpdateIndex({
    required String indexPath,
  }) {
    final sink = RustStreamSink<IndexActionState>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(indexPath, serializer);
            sse_encode_StreamSink_index_action_state_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 34,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiTagReaderUpdateIndexConstMeta,
          argValues: [indexPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTagReaderUpdateIndexConstMeta =>
      const TaskConstMeta(
        debugName: "update_index",
        argNames: ["indexPath", "sink"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LyricLine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LyricLine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SmtcFlutter => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SmtcFlutter => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SmtcFlutter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LyricLine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LyricLineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SmtcFlutter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LyricLine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LyricLineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SmtcFlutter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<IndexActionState> dco_decode_StreamSink_index_action_state_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SMTCControlEvent> dco_decode_StreamSink_smtc_control_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  LyricLineOwned dco_decode_box_autoadd_lyric_line_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_lyric_line_owned(raw);
  }

  @protected
  LyricWordOwned dco_decode_box_autoadd_lyric_word_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_lyric_word_owned(raw);
  }

  @protected
  TTMLLyricOwned dco_decode_box_autoadd_ttml_lyric_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ttml_lyric_owned(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IndexActionState dco_decode_index_action_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IndexActionState(
      progress: dco_decode_f_64(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LyricLineOwned> dco_decode_list_lyric_line_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lyric_line_owned).toList();
  }

  @protected
  List<LyricWordOwned> dco_decode_list_lyric_word_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lyric_word_owned).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, List<String>)> dco_decode_list_record_string_list_string(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_string)
        .toList();
  }

  @protected
  LyricLineOwned dco_decode_lyric_line_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return LyricLineOwned(
      words: dco_decode_list_lyric_word_owned(arr[0]),
      translatedLyric: dco_decode_String(arr[1]),
      romanLyric: dco_decode_String(arr[2]),
      isBg: dco_decode_bool(arr[3]),
      isDuet: dco_decode_bool(arr[4]),
      startTime: dco_decode_u_64(arr[5]),
      endTime: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  LyricWordOwned dco_decode_lyric_word_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LyricWordOwned(
      startTime: dco_decode_u_64(arr[0]),
      endTime: dco_decode_u_64(arr[1]),
      word: dco_decode_String(arr[2]),
      romanWord: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (String, List<String>) dco_decode_record_string_list_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_list_String(arr[1]));
  }

  @protected
  SMTCControlEvent dco_decode_smtc_control_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SMTCControlEvent.values[raw as int];
  }

  @protected
  SMTCState dco_decode_smtc_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SMTCState.values[raw as int];
  }

  @protected
  TTMLLyricOwned dco_decode_ttml_lyric_owned(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TTMLLyricOwned(
      lines: dco_decode_list_lyric_line_owned(arr[0]),
      metadata: dco_decode_list_record_string_list_string(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SmtcFlutter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LyricLine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LyricLineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SmtcFlutter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LyricLine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LyricLineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SmtcFlutter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SmtcFlutterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<IndexActionState> sse_decode_StreamSink_index_action_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SMTCControlEvent> sse_decode_StreamSink_smtc_control_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  LyricLineOwned sse_decode_box_autoadd_lyric_line_owned(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_lyric_line_owned(deserializer));
  }

  @protected
  LyricWordOwned sse_decode_box_autoadd_lyric_word_owned(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_lyric_word_owned(deserializer));
  }

  @protected
  TTMLLyricOwned sse_decode_box_autoadd_ttml_lyric_owned(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ttml_lyric_owned(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IndexActionState sse_decode_index_action_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_f_64(deserializer);
    var var_message = sse_decode_String(deserializer);
    return IndexActionState(progress: var_progress, message: var_message);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LyricLineOwned> sse_decode_list_lyric_line_owned(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LyricLineOwned>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lyric_line_owned(deserializer));
    }
    return ans_;
  }

  @protected
  List<LyricWordOwned> sse_decode_list_lyric_word_owned(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LyricWordOwned>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lyric_word_owned(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, List<String>)> sse_decode_list_record_string_list_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, List<String>)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_string(deserializer));
    }
    return ans_;
  }

  @protected
  LyricLineOwned sse_decode_lyric_line_owned(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_words = sse_decode_list_lyric_word_owned(deserializer);
    var var_translatedLyric = sse_decode_String(deserializer);
    var var_romanLyric = sse_decode_String(deserializer);
    var var_isBg = sse_decode_bool(deserializer);
    var var_isDuet = sse_decode_bool(deserializer);
    var var_startTime = sse_decode_u_64(deserializer);
    var var_endTime = sse_decode_u_64(deserializer);
    return LyricLineOwned(
      words: var_words,
      translatedLyric: var_translatedLyric,
      romanLyric: var_romanLyric,
      isBg: var_isBg,
      isDuet: var_isDuet,
      startTime: var_startTime,
      endTime: var_endTime,
    );
  }

  @protected
  LyricWordOwned sse_decode_lyric_word_owned(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startTime = sse_decode_u_64(deserializer);
    var var_endTime = sse_decode_u_64(deserializer);
    var var_word = sse_decode_String(deserializer);
    var var_romanWord = sse_decode_String(deserializer);
    return LyricWordOwned(
      startTime: var_startTime,
      endTime: var_endTime,
      word: var_word,
      romanWord: var_romanWord,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, List<String>) sse_decode_record_string_list_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SMTCControlEvent sse_decode_smtc_control_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SMTCControlEvent.values[inner];
  }

  @protected
  SMTCState sse_decode_smtc_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SMTCState.values[inner];
  }

  @protected
  TTMLLyricOwned sse_decode_ttml_lyric_owned(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_lyric_line_owned(deserializer);
    var var_metadata = sse_decode_list_record_string_list_string(deserializer);
    return TTMLLyricOwned(lines: var_lines, metadata: var_metadata);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    SmtcFlutter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SmtcFlutterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
    LyricLine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LyricLineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    SmtcFlutter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SmtcFlutterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLyricLine(
    LyricLine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LyricLineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSMTCFlutter(
    SmtcFlutter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SmtcFlutterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_index_action_state_Sse(
    RustStreamSink<IndexActionState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_index_action_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_smtc_control_event_Sse(
    RustStreamSink<SMTCControlEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_smtc_control_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_lyric_line_owned(
    LyricLineOwned self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_lyric_line_owned(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_lyric_word_owned(
    LyricWordOwned self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_lyric_word_owned(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ttml_lyric_owned(
    TTMLLyricOwned self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ttml_lyric_owned(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_index_action_state(
    IndexActionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.progress, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lyric_line_owned(
    List<LyricLineOwned> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lyric_line_owned(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lyric_word_owned(
    List<LyricWordOwned> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lyric_word_owned(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_string(
    List<(String, List<String>)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_string(item, serializer);
    }
  }

  @protected
  void sse_encode_lyric_line_owned(
    LyricLineOwned self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_lyric_word_owned(self.words, serializer);
    sse_encode_String(self.translatedLyric, serializer);
    sse_encode_String(self.romanLyric, serializer);
    sse_encode_bool(self.isBg, serializer);
    sse_encode_bool(self.isDuet, serializer);
    sse_encode_u_64(self.startTime, serializer);
    sse_encode_u_64(self.endTime, serializer);
  }

  @protected
  void sse_encode_lyric_word_owned(
    LyricWordOwned self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.startTime, serializer);
    sse_encode_u_64(self.endTime, serializer);
    sse_encode_String(self.word, serializer);
    sse_encode_String(self.romanWord, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_list_string(
    (String, List<String>) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_String(self.$2, serializer);
  }

  @protected
  void sse_encode_smtc_control_event(
    SMTCControlEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_smtc_state(SMTCState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ttml_lyric_owned(
    TTMLLyricOwned self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_lyric_line_owned(self.lines, serializer);
    sse_encode_list_record_string_list_string(self.metadata, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class LyricLineImpl extends RustOpaque implements LyricLine {
  // Not to be used by end users
  LyricLineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LyricLineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LyricLine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LyricLine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LyricLinePtr,
  );
}

@sealed
class SmtcFlutterImpl extends RustOpaque implements SmtcFlutter {
  // Not to be used by end users
  SmtcFlutterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SmtcFlutterImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SmtcFlutter,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SmtcFlutter,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SmtcFlutterPtr,
  );

  /// Apis for Flutter
  Future<void> close() =>
      RustLib.instance.api.crateApiSmtcFlutterSmtcFlutterClose(that: this);

  /// Apis for Flutter
  Stream<SMTCControlEvent> subscribeToControlEvents() => RustLib.instance.api
      .crateApiSmtcFlutterSmtcFlutterSubscribeToControlEvents(that: this);

  /// Apis for Flutter
  Future<void> updateDisplay({
    required String title,
    required String artist,
    required String album,
    required int duration,
    required String path,
  }) => RustLib.instance.api.crateApiSmtcFlutterSmtcFlutterUpdateDisplay(
    that: this,
    title: title,
    artist: artist,
    album: album,
    duration: duration,
    path: path,
  );

  /// Apis for Flutter
  Future<void> updateState({required SMTCState state}) => RustLib.instance.api
      .crateApiSmtcFlutterSmtcFlutterUpdateState(that: this, state: state);

  /// progress, duration: ms
  /// Apis for Flutter
  Future<void> updateTimeProperties({required int progress}) =>
      RustLib.instance.api.crateApiSmtcFlutterSmtcFlutterUpdateTimeProperties(
        that: this,
        progress: progress,
      );
}
