// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `_parse_ttml`

/// TTML 格式
Future<TTMLLyricOwned> parseTtml({required String content}) =>
    RustLib.instance.api.crateApiLyricParserTtmlReadParseTtml(content: content);
