// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// LRC 格式
Future<List<LyricLineOwned>> parseLrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserApiParseLrc(content: content);

Future<String> stringifyLrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyLrc(lines: lines);

/// ESLyric 格式
Future<List<LyricLineOwned>> parseEslrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserApiParseEslrc(content: content);

Future<String> stringifyEslrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyEslrc(lines: lines);

/// YRC 格式（网易云）
Future<List<LyricLineOwned>> parseYrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserApiParseYrc(content: content);

Future<String> stringifyYrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyYrc(lines: lines);

/// QRC 格式（QQ音乐）
Future<List<LyricLineOwned>> parseQrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserApiParseQrc(content: content);

Future<String> stringifyQrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyQrc(lines: lines);

/// LYS 格式（Lyricify）
Future<List<LyricLineOwned>> parseLys({required String content}) =>
    RustLib.instance.api.crateApiLyricParserApiParseLys(content: content);

Future<String> stringifyLys({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyLys(lines: lines);

/// ASS 格式（仅导出）
Future<String> stringifyAss({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyAss(lines: lines);

/// TTML 格式
Future<TTMLLyricOwned> parseTtml({required String content}) =>
    RustLib.instance.api.crateApiLyricParserApiParseTtml(content: content);

Future<String> stringifyTtml({required TTMLLyricOwned ttml}) =>
    RustLib.instance.api.crateApiLyricParserApiStringifyTtml(ttml: ttml);
