// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_stringify_ass`, `write_timestamp`

Future<String> stringifyAss({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserAssStringifyAss(lines: lines);
