// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_hex`

Future<String> decryptQrcRaw({required U8 data}) =>
    RustLib.instance.api.crateApiLyricParserEqrcDecryptQrcRaw(data: data);

Future<String> decryptQrcHex({required String hexData}) =>
    RustLib.instance.api.crateApiLyricParserEqrcDecryptQrcHex(hexData: hexData);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<[u8]>>
abstract class U8 implements RustOpaqueInterface {}
