// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_parse_eslrc`, `_stringify_eslrc`, `parse_line`

/// ESLyric 格式
Future<List<LyricLineOwned>> parseEslrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserEslrcParseEslrc(content: content);

Future<String> stringifyEslrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserEslrcStringifyEslrc(lines: lines);
