// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_parse_lys`, `_stringify_lys`, `parse_line`, `parse_property`, `parse_word_time`, `parse_word`, `parse_words`, `process_time`

/// LYS 格式（Lyricify）
Future<List<LyricLineOwned>> parseLys({required String content}) =>
    RustLib.instance.api.crateApiLyricParserLysParseLys(content: content);

Future<String> stringifyLys({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserLysStringifyLys(lines: lines);
