// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_parse_qrc`, `_stringify_qrc`, `parse_line`, `parse_time`, `parse_word_time`, `parse_word`, `parse_words`, `process_time`

/// QRC 格式（QQ音乐）
Future<List<LyricLineOwned>> parseQrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserQrcParseQrc(content: content);

Future<String> stringifyQrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserQrcStringifyQrc(lines: lines);
