// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../lyric_parser.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_parse_yrc`, `_stringify_yrc`, `parse_line`, `parse_time`, `parse_word_time`, `parse_words`, `process_time`

/// YRC 格式（网易云）
Future<List<LyricLineOwned>> parseYrc({required String content}) =>
    RustLib.instance.api.crateApiLyricParserYrcParseYrc(content: content);

Future<String> stringifyYrc({required List<LyricLineOwned> lines}) =>
    RustLib.instance.api.crateApiLyricParserYrcStringifyYrc(lines: lines);
