import './lyric_model.dart';

/// 示例歌词数据
/// 包含逐字信息和翻译
class SampleLyrics {
  static Lyrics get demoSong => Lyrics(
    title: '夜曲',
    artist: '周杰伦',
    lines: [
      LyricLine(
        start: const Duration(seconds: 0, milliseconds: 500),
        end: const Duration(seconds: 4, milliseconds: 0),
        text: '一群嗜血的蚂蚁',
        translation: 'A swarm of bloodthirsty ants',
        words: [
          LyricWord(text: '一', start: const Duration(seconds: 0, milliseconds: 500), end: const Duration(seconds: 0, milliseconds: 800)),
          LyricWord(text: '群', start: const Duration(seconds: 0, milliseconds: 800), end: const Duration(seconds: 1, milliseconds: 100)),
          LyricWord(text: '嗜', start: const Duration(seconds: 1, milliseconds: 100), end: const Duration(seconds: 1, milliseconds: 400)),
          LyricWord(text: '血', start: const Duration(seconds: 1, milliseconds: 400), end: const Duration(seconds: 1, milliseconds: 700)),
          LyricWord(text: '的', start: const Duration(seconds: 1, milliseconds: 700), end: const Duration(seconds: 2, milliseconds: 0)),
          LyricWord(text: '蚂', start: const Duration(seconds: 2, milliseconds: 0), end: const Duration(seconds: 2, milliseconds: 400)),
          LyricWord(text: '蚁', start: const Duration(seconds: 2, milliseconds: 400), end: const Duration(seconds: 3, milliseconds: 0)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 4, milliseconds: 0),
        end: const Duration(seconds: 8, milliseconds: 0),
        text: '被腐肉所吸引',
        translation: 'Attracted by rotting flesh',
        words: [
          LyricWord(text: '被', start: const Duration(seconds: 4, milliseconds: 0), end: const Duration(seconds: 4, milliseconds: 300)),
          LyricWord(text: '腐', start: const Duration(seconds: 4, milliseconds: 300), end: const Duration(seconds: 4, milliseconds: 600)),
          LyricWord(text: '肉', start: const Duration(seconds: 4, milliseconds: 600), end: const Duration(seconds: 5, milliseconds: 0)),
          LyricWord(text: '所', start: const Duration(seconds: 5, milliseconds: 0), end: const Duration(seconds: 5, milliseconds: 300)),
          LyricWord(text: '吸', start: const Duration(seconds: 5, milliseconds: 300), end: const Duration(seconds: 6, milliseconds: 0)),
          LyricWord(text: '引', start: const Duration(seconds: 6, milliseconds: 0), end: const Duration(seconds: 7, milliseconds: 0)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 8, milliseconds: 0),
        end: const Duration(seconds: 12, milliseconds: 0),
        text: '我面无表情 看孤独的风景',
        translation: 'I have no expression on my face, watching the lonely scenery',
        words: [
          LyricWord(text: '我', start: const Duration(seconds: 8, milliseconds: 0), end: const Duration(seconds: 8, milliseconds: 400)),
          LyricWord(text: '面', start: const Duration(seconds: 8, milliseconds: 400), end: const Duration(seconds: 8, milliseconds: 800)),
          LyricWord(text: '无', start: const Duration(seconds: 8, milliseconds: 800), end: const Duration(seconds: 9, milliseconds: 200)),
          LyricWord(text: '表', start: const Duration(seconds: 9, milliseconds: 200), end: const Duration(seconds: 9, milliseconds: 600)),
          LyricWord(text: '情', start: const Duration(seconds: 9, milliseconds: 600), end: const Duration(seconds: 10, milliseconds: 0)),
          LyricWord(text: '看', start: const Duration(seconds: 10, milliseconds: 0), end: const Duration(seconds: 10, milliseconds: 300)),
          LyricWord(text: '孤', start: const Duration(seconds: 10, milliseconds: 300), end: const Duration(seconds: 10, milliseconds: 600)),
          LyricWord(text: '独', start: const Duration(seconds: 10, milliseconds: 600), end: const Duration(seconds: 11, milliseconds: 0)),
          LyricWord(text: '的', start: const Duration(seconds: 11, milliseconds: 0), end: const Duration(seconds: 11, milliseconds: 300)),
          LyricWord(text: '风', start: const Duration(seconds: 11, milliseconds: 300), end: const Duration(seconds: 11, milliseconds: 500)),
          LyricWord(text: '景', start: const Duration(seconds: 11, milliseconds: 500), end: const Duration(seconds: 11, milliseconds: 800)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 12, milliseconds: 0),
        end: const Duration(seconds: 16, milliseconds: 0),
        text: '失去你',
        // 这行没有翻译，测试不同行高
        words: [
          LyricWord(text: '失', start: const Duration(seconds: 12, milliseconds: 0), end: const Duration(seconds: 12, milliseconds: 400)),
          LyricWord(text: '去', start: const Duration(seconds: 12, milliseconds: 400), end: const Duration(seconds: 12, milliseconds: 800)),
          LyricWord(text: '你', start: const Duration(seconds: 12, milliseconds: 800), end: const Duration(seconds: 15, milliseconds: 0)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 16, milliseconds: 0),
        end: const Duration(seconds: 20, milliseconds: 0),
        text: '爱恨都不能说明',
        translation: 'Love and hate can\'t explain anything',
        words: [
          LyricWord(text: '爱', start: const Duration(seconds: 16, milliseconds: 0), end: const Duration(seconds: 16, milliseconds: 400)),
          LyricWord(text: '恨', start: const Duration(seconds: 16, milliseconds: 400), end: const Duration(seconds: 16, milliseconds: 800)),
          LyricWord(text: '都', start: const Duration(seconds: 16, milliseconds: 800), end: const Duration(seconds: 17, milliseconds: 200)),
          LyricWord(text: '不', start: const Duration(seconds: 17, milliseconds: 200), end: const Duration(seconds: 17, milliseconds: 600)),
          LyricWord(text: '能', start: const Duration(seconds: 17, milliseconds: 600), end: const Duration(seconds: 18, milliseconds: 0)),
          LyricWord(text: '说', start: const Duration(seconds: 18, milliseconds: 0), end: const Duration(seconds: 18, milliseconds: 400)),
          LyricWord(text: '明', start: const Duration(seconds: 18, milliseconds: 400), end: const Duration(seconds: 19, milliseconds: 500)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 20, milliseconds: 0),
        end: const Duration(seconds: 24, milliseconds: 0),
        text: '什么叫做爱情的证据',
        // 无翻译
        words: [
          LyricWord(text: '什', start: const Duration(seconds: 20, milliseconds: 0), end: const Duration(seconds: 20, milliseconds: 300)),
          LyricWord(text: '么', start: const Duration(seconds: 20, milliseconds: 300), end: const Duration(seconds: 20, milliseconds: 600)),
          LyricWord(text: '叫', start: const Duration(seconds: 20, milliseconds: 600), end: const Duration(seconds: 20, milliseconds: 900)),
          LyricWord(text: '做', start: const Duration(seconds: 20, milliseconds: 900), end: const Duration(seconds: 21, milliseconds: 200)),
          LyricWord(text: '爱', start: const Duration(seconds: 21, milliseconds: 200), end: const Duration(seconds: 21, milliseconds: 500)),
          LyricWord(text: '情', start: const Duration(seconds: 21, milliseconds: 500), end: const Duration(seconds: 21, milliseconds: 800)),
          LyricWord(text: '的', start: const Duration(seconds: 21, milliseconds: 800), end: const Duration(seconds: 22, milliseconds: 100)),
          LyricWord(text: '证', start: const Duration(seconds: 22, milliseconds: 100), end: const Duration(seconds: 22, milliseconds: 500)),
          LyricWord(text: '据', start: const Duration(seconds: 22, milliseconds: 500), end: const Duration(seconds: 23, milliseconds: 500)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 24, milliseconds: 0),
        end: const Duration(seconds: 28, milliseconds: 0),
        text: '为你弹奏萧邦的夜曲',
        translation: 'Playing Chopin\'s Nocturne for you',
        words: [
          LyricWord(text: '为', start: const Duration(seconds: 24, milliseconds: 0), end: const Duration(seconds: 24, milliseconds: 300)),
          LyricWord(text: '你', start: const Duration(seconds: 24, milliseconds: 300), end: const Duration(seconds: 24, milliseconds: 600)),
          LyricWord(text: '弹', start: const Duration(seconds: 24, milliseconds: 600), end: const Duration(seconds: 25, milliseconds: 0)),
          LyricWord(text: '奏', start: const Duration(seconds: 25, milliseconds: 0), end: const Duration(seconds: 25, milliseconds: 300)),
          LyricWord(text: '萧', start: const Duration(seconds: 25, milliseconds: 300), end: const Duration(seconds: 25, milliseconds: 700)),
          LyricWord(text: '邦', start: const Duration(seconds: 25, milliseconds: 700), end: const Duration(seconds: 26, milliseconds: 100)),
          LyricWord(text: '的', start: const Duration(seconds: 26, milliseconds: 100), end: const Duration(seconds: 26, milliseconds: 400)),
          LyricWord(text: '夜', start: const Duration(seconds: 26, milliseconds: 400), end: const Duration(seconds: 26, milliseconds: 800)),
          LyricWord(text: '曲', start: const Duration(seconds: 26, milliseconds: 800), end: const Duration(seconds: 27, milliseconds: 500)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 28, milliseconds: 0),
        end: const Duration(seconds: 32, milliseconds: 0),
        text: '纪念我死去的爱情',
        translation: 'Commemorating my dead love',
        words: [
          LyricWord(text: '纪', start: const Duration(seconds: 28, milliseconds: 0), end: const Duration(seconds: 28, milliseconds: 400)),
          LyricWord(text: '念', start: const Duration(seconds: 28, milliseconds: 400), end: const Duration(seconds: 28, milliseconds: 800)),
          LyricWord(text: '我', start: const Duration(seconds: 28, milliseconds: 800), end: const Duration(seconds: 29, milliseconds: 200)),
          LyricWord(text: '死', start: const Duration(seconds: 29, milliseconds: 200), end: const Duration(seconds: 29, milliseconds: 600)),
          LyricWord(text: '去', start: const Duration(seconds: 29, milliseconds: 600), end: const Duration(seconds: 30, milliseconds: 0)),
          LyricWord(text: '的', start: const Duration(seconds: 30, milliseconds: 0), end: const Duration(seconds: 30, milliseconds: 300)),
          LyricWord(text: '爱', start: const Duration(seconds: 30, milliseconds: 300), end: const Duration(seconds: 30, milliseconds: 700)),
          LyricWord(text: '情', start: const Duration(seconds: 30, milliseconds: 700), end: const Duration(seconds: 31, milliseconds: 500)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 32, milliseconds: 0),
        end: const Duration(seconds: 36, milliseconds: 0),
        text: '而我为你隐姓埋名',
        translation: 'And I hide my name for you',
        words: [
          LyricWord(text: '而', start: const Duration(seconds: 32, milliseconds: 0), end: const Duration(seconds: 32, milliseconds: 300)),
          LyricWord(text: '我', start: const Duration(seconds: 32, milliseconds: 300), end: const Duration(seconds: 32, milliseconds: 600)),
          LyricWord(text: '为', start: const Duration(seconds: 32, milliseconds: 600), end: const Duration(seconds: 33, milliseconds: 0)),
          LyricWord(text: '你', start: const Duration(seconds: 33, milliseconds: 0), end: const Duration(seconds: 33, milliseconds: 300)),
          LyricWord(text: '隐', start: const Duration(seconds: 33, milliseconds: 300), end: const Duration(seconds: 33, milliseconds: 700)),
          LyricWord(text: '姓', start: const Duration(seconds: 33, milliseconds: 700), end: const Duration(seconds: 34, milliseconds: 100)),
          LyricWord(text: '埋', start: const Duration(seconds: 34, milliseconds: 100), end: const Duration(seconds: 34, milliseconds: 500)),
          LyricWord(text: '名', start: const Duration(seconds: 34, milliseconds: 500), end: const Duration(seconds: 35, milliseconds: 500)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 36, milliseconds: 0),
        end: const Duration(seconds: 40, milliseconds: 0),
        text: '在月光下弹琴',
        translation: 'Playing piano under the moonlight',
        words: [
          LyricWord(text: '在', start: const Duration(seconds: 36, milliseconds: 0), end: const Duration(seconds: 36, milliseconds: 400)),
          LyricWord(text: '月', start: const Duration(seconds: 36, milliseconds: 400), end: const Duration(seconds: 36, milliseconds: 800)),
          LyricWord(text: '光', start: const Duration(seconds: 36, milliseconds: 800), end: const Duration(seconds: 37, milliseconds: 200)),
          LyricWord(text: '下', start: const Duration(seconds: 37, milliseconds: 200), end: const Duration(seconds: 37, milliseconds: 600)),
          LyricWord(text: '弹', start: const Duration(seconds: 37, milliseconds: 600), end: const Duration(seconds: 38, milliseconds: 0)),
          LyricWord(text: '琴', start: const Duration(seconds: 38, milliseconds: 0), end: const Duration(seconds: 39, milliseconds: 0)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 40, milliseconds: 0),
        end: const Duration(seconds: 44, milliseconds: 0),
        text: '对你心跳的感应',
        // 无翻译
        words: [
          LyricWord(text: '对', start: const Duration(seconds: 40, milliseconds: 0), end: const Duration(seconds: 40, milliseconds: 300)),
          LyricWord(text: '你', start: const Duration(seconds: 40, milliseconds: 300), end: const Duration(seconds: 40, milliseconds: 600)),
          LyricWord(text: '心', start: const Duration(seconds: 40, milliseconds: 600), end: const Duration(seconds: 41, milliseconds: 0)),
          LyricWord(text: '跳', start: const Duration(seconds: 41, milliseconds: 0), end: const Duration(seconds: 41, milliseconds: 400)),
          LyricWord(text: '的', start: const Duration(seconds: 41, milliseconds: 400), end: const Duration(seconds: 41, milliseconds: 700)),
          LyricWord(text: '感', start: const Duration(seconds: 41, milliseconds: 700), end: const Duration(seconds: 42, milliseconds: 200)),
          LyricWord(text: '应', start: const Duration(seconds: 42, milliseconds: 200), end: const Duration(seconds: 43, milliseconds: 0)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 44, milliseconds: 0),
        end: const Duration(seconds: 48, milliseconds: 0),
        text: '还是如此温热亲近',
        translation: 'Is still so warm and close',
        words: [
          LyricWord(text: '还', start: const Duration(seconds: 44, milliseconds: 0), end: const Duration(seconds: 44, milliseconds: 300)),
          LyricWord(text: '是', start: const Duration(seconds: 44, milliseconds: 300), end: const Duration(seconds: 44, milliseconds: 600)),
          LyricWord(text: '如', start: const Duration(seconds: 44, milliseconds: 600), end: const Duration(seconds: 45, milliseconds: 0)),
          LyricWord(text: '此', start: const Duration(seconds: 45, milliseconds: 0), end: const Duration(seconds: 45, milliseconds: 400)),
          LyricWord(text: '温', start: const Duration(seconds: 45, milliseconds: 400), end: const Duration(seconds: 45, milliseconds: 800)),
          LyricWord(text: '热', start: const Duration(seconds: 45, milliseconds: 800), end: const Duration(seconds: 46, milliseconds: 200)),
          LyricWord(text: '亲', start: const Duration(seconds: 46, milliseconds: 200), end: const Duration(seconds: 46, milliseconds: 600)),
          LyricWord(text: '近', start: const Duration(seconds: 46, milliseconds: 600), end: const Duration(seconds: 47, milliseconds: 500)),
        ],
      ),
      LyricLine(
        start: const Duration(seconds: 48, milliseconds: 0),
        end: const Duration(seconds: 52, milliseconds: 0),
        text: '怀念你那鲜红的唇印',
        translation: 'Missing your bright red lip print',
        words: [
          LyricWord(text: '怀', start: const Duration(seconds: 48, milliseconds: 0), end: const Duration(seconds: 48, milliseconds: 300)),
          LyricWord(text: '念', start: const Duration(seconds: 48, milliseconds: 300), end: const Duration(seconds: 48, milliseconds: 600)),
          LyricWord(text: '你', start: const Duration(seconds: 48, milliseconds: 600), end: const Duration(seconds: 49, milliseconds: 0)),
          LyricWord(text: '那', start: const Duration(seconds: 49, milliseconds: 0), end: const Duration(seconds: 49, milliseconds: 300)),
          LyricWord(text: '鲜', start: const Duration(seconds: 49, milliseconds: 300), end: const Duration(seconds: 49, milliseconds: 700)),
          LyricWord(text: '红', start: const Duration(seconds: 49, milliseconds: 700), end: const Duration(seconds: 50, milliseconds: 100)),
          LyricWord(text: '的', start: const Duration(seconds: 50, milliseconds: 100), end: const Duration(seconds: 50, milliseconds: 400)),
          LyricWord(text: '唇', start: const Duration(seconds: 50, milliseconds: 400), end: const Duration(seconds: 50, milliseconds: 800)),
          LyricWord(text: '印', start: const Duration(seconds: 50, milliseconds: 800), end: const Duration(seconds: 51, milliseconds: 500)),
        ],
      ),
    ],
  );
}
