// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<IResultU8U64> parseHour({required List<int> input}) => RustLib
    .instance
    .api
    .crateApiLyricParserTtmlReadUtilsParseHour(input: input);

Future<IResultU8U64> parseMinutesOrSeconds({required List<int> input}) =>
    RustLib.instance.api.crateApiLyricParserTtmlReadUtilsParseMinutesOrSeconds(
      input: input,
    );

Future<IResultU8U64> parseFraction({required List<int> input}) => RustLib
    .instance
    .api
    .crateApiLyricParserTtmlReadUtilsParseFraction(input: input);

Future<IResultU8U64> parseTimestamp({required List<int> input}) => RustLib
    .instance
    .api
    .crateApiLyricParserTtmlReadUtilsParseTimestamp(input: input);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IResult < & [u8] , u64 >>>
abstract class IResultU8U64 implements RustOpaqueInterface {}
