// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import '../qdec.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bitnum`, `bitnumintl`, `bitnumintr`, `f`, `generate_sp_tables`, `inv_ip`, `ip`, `sboxbit`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`

Future<U8Array6Array16> desKeySetup({
  required List<int> key,
  required DesMode mode,
}) => RustLib.instance.api.crateApiLyricParserEqrcQdecDesDesKeySetup(
  key: key,
  mode: mode,
);

Future<U8Array8> desCrypt({
  required List<int> input,
  required U8Array6Array16 keySchedule,
}) => RustLib.instance.api.crateApiLyricParserEqrcQdecDesDesCrypt(
  input: input,
  keySchedule: keySchedule,
);

Future<U8Array6Array16Array3> threeDesKeySetup({
  required List<int> key,
  required DesMode mode,
}) => RustLib.instance.api.crateApiLyricParserEqrcQdecDesThreeDesKeySetup(
  key: key,
  mode: mode,
);

Future<void> threeDesCrypt({
  required U88 input,
  required U8Array6Array16Array3 keySchedule,
}) => RustLib.instance.api.crateApiLyricParserEqrcQdecDesThreeDesCrypt(
  input: input,
  keySchedule: keySchedule,
);

enum DesMode { encrypt, decrypt }

class U8Array8 extends NonGrowableListView<int> {
  static const arraySize = 8;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array8(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array8.init() : this(Uint8List(arraySize));
}
