// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

class LyricLineParsed {
  final BigInt start;
  final BigInt end;
  final String text;
  final List<LyricWordParsed> words;
  final String translation;

  const LyricLineParsed({
    required this.start,
    required this.end,
    required this.text,
    required this.words,
    required this.translation,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      end.hashCode ^
      text.hashCode ^
      words.hashCode ^
      translation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLineParsed &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          text == other.text &&
          words == other.words &&
          translation == other.translation;
}

class LyricWordParsed {
  final String text;
  final BigInt start;
  final BigInt end;

  const LyricWordParsed({
    required this.text,
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => text.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricWordParsed &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          start == other.start &&
          end == other.end;
}

class ParseResult {
  final List<LyricLineParsed> lines;
  final String format;

  const ParseResult({required this.lines, required this.format});

  @override
  int get hashCode => lines.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseResult &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          format == other.format;
}
